[package]
name = "nonogram-term"
version = "0.1.0"
authors = ["Harrison McCullough <mccullough.harrison@gmail.com>"]
edition = "2018"

[dependencies]
nonogram = { path = "../nonogram" }
cursive = "0.11"
